### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by kmo-scalepoint** [DabblerDK/MEP-HW-SMD#1]
Hej 
Har i link til den MAX3232 , og de smd condensator i bruger

**Comment by glynge** [comment]
Hej kmo-scalepoint

Ja, SMD kondensatorerne er 0805'ere i 100nF - disse er dem jeg bestilte sidst: https://www.ebay.com/itm/255486850064
Men er det ikke noget du gør meget i, vil jeg foreslå dig at købe et SMD 0805 komponentsortiment med både kondensatorer og modstande (det startede vi også med).

Mht. MAX3232'eren bestilte jeg disse sidste gang:
THT er DIP-16 pakken: https://www.ebay.com/itm/302100181797 (pas på - der er mange fakes derude)
SMD er SOP-16 pakken: https://www.ebay.com/itm/125374809880 - men den er vist pillet ned. Forrige gang var det https://www.ebay.com/itm/291205964463
