### ISSUE TITLE
Hej

### ISSUE THREAD

**Issue by pulsejets** [DabblerDK/MEP-HW-SMD#2]
Kan i ikke gøre så man kan lave et pull request , så man kan bidrage

**Comment by glynge** [comment]
Øh, jeg er ikke GitHub 100m mester, men repositoriet er så vidt jeg kan se opsat ligesom vores MEP-SW-ESP32 repository - og der har vi da fået en pull request?
Har du en idé til hvad vi har opsat forkert?

**Comment by pulsejets** [comment]
Jeg er heller ikke 100 meter mester i git, men jeg tror du har et pull request nu

**Comment by glynge** [comment]
Jeps - virkede perfekt. Så jeg tror det er opsat som det skal være :-)
